# Generated by Django 4.1.5 on 2023-01-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Задача')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Выдана')),
                ('period_of_execution', models.DateField(verbose_name='Срок(дата) исполнения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Исполнено')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretary.executor', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['id'],
            },
        ),
    ]
